//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public int Id { get; set; }
        public string Ilgis { get; set; }
        public string Plotis { get; set; }
        public string Ratai { get; set; }
        public string Guoliai { get; set; }
        public string MaksimalusSvoris { get; set; }
        public string Spalva { get; set; }
        public string Asys { get; set; }
        public string Paskirtis { get; set; }
        public string Gamintojas { get; set; }
        public string Dydis { get; set; }
        public string Storis { get; set; }
        public string Kietumas { get; set; }
        public string Skirta { get; set; }
    }
}
